### ISSUE TITLE
关于模型在计算I时使用的图结构

### ISSUE THREAD

**Issue by hexin5515** [EdisonLeeeee/GUARD#2]
您好，我在阅读您的文章时发现一个问题，当使用clean graph的degree作为模型的输入时，获得的defense效果要比使用attacked graph的degree作为模型输入好上不少，您是否也注意到过这个问题呢，对于这个结果您怎么看，只是想和您探讨一下，期待您的回复！

**Comment by EdisonLeeeee** [comment]
您好，感谢您对我们工作的关注！

根据我们论文的结果：对抗攻击倾向于加边且攻击低度节点，因此会导致攻击后低度节点的degree显著提高，从而影响节点的Influence score（也就是I）。因此，使用clean graph的degree作为模型的输入更为合理；而如果使用attacked graph的degree作为模型输入的话，由于大部分低度节点的度都提高了，计算出来的Influence score并不能准确反映节点的影响力

**Comment by hexin5515** [comment]
谢谢回复！
